server:
  port: 8084

spring:
  application:
    name: prueba-practica-accenture
  jpa:
    hibernate:
      ddl-auto: create-drop # Eliminar esta linea para producción, es solo para dev
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}